version: "3"

services:
  redis:
    image: redis:7
    command: "redis-server --loglevel warning"
    volumes:
      - redis_data:/data/
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  redis_data:
